[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string[]]$ResponsePaths,
  [Parameter(Mandatory=$true)][string]$OutputPath,
  [string]$ProviderRunId='',
  [string]$TaskId=''
)
$ErrorActionPreference='Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
function Resolve-ProjectFile([string]$p){$f=if([IO.Path]::IsPathRooted($p)){[IO.Path]::GetFullPath($p)}else{[IO.Path]::GetFullPath((Join-Path $root $p))};if(-not $f.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)){throw "BLOCKED_WEB_RESPONSE_PATH_OUTSIDE_PROJECT:$p"};if(-not(Test-Path -LiteralPath $f -PathType Leaf)){throw "BLOCKED_WEB_RESPONSE_MISSING:$p"};$f}
$responses=[Collections.Generic.List[object]]::new();$seen=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);$hashes=@()
foreach($path in $ResponsePaths){$full=Resolve-ProjectFile $path;$text=[Text.UTF8Encoding]::new($false,$true).GetString([IO.File]::ReadAllBytes($full));try{$doc=$text|ConvertFrom-Json}catch{throw "BLOCKED_WEB_RESPONSE_INVALID_JSON:$path"};if([string]$doc.recordType -cne 'AiWebDesignModelResponse'){throw "BLOCKED_WEB_RESPONSE_CONTRACT_MISMATCH:$path"};if([string]::IsNullOrWhiteSpace([string]$doc.taskId)){throw "BLOCKED_WEB_RESPONSE_TASK_ID_MISSING:$path"};if([string]::IsNullOrWhiteSpace($TaskId)){$TaskId=[string]$doc.taskId}elseif([string]$doc.taskId -cne $TaskId){throw "BLOCKED_WEB_RESPONSE_TASK_ID_MISMATCH:$path"};if([string]::IsNullOrWhiteSpace([string]$doc.providerRunId)){throw "BLOCKED_WEB_RESPONSE_PROVIDER_ID_MISSING:$path"};if([string]::IsNullOrWhiteSpace($ProviderRunId)){$ProviderRunId=[string]$doc.providerRunId}elseif([string]$doc.providerRunId -cne $ProviderRunId){throw "BLOCKED_WEB_RESPONSE_PROVIDER_RUN_MISMATCH:$path"};foreach($entry in @($doc.responses)){if($null -eq $entry -or [string]::IsNullOrWhiteSpace([string]$entry.phase) -or [string]$entry.generationMode -notin @('creative-divergence','engineering','stable') -or [int]$entry.round -lt 0 -or @($entry.outputs).Count -lt 1){throw "BLOCKED_WEB_RESPONSE_STAGE_IDENTITY_INVALID:$path"};$key=('{0}|{1}|{2}' -f $entry.phase,$entry.generationMode,[int]$entry.round);if(-not $seen.Add($key)){throw "BLOCKED_WEB_RESPONSE_STAGE_DUPLICATE:$key"};foreach($o in @($entry.outputs)){if([string]::IsNullOrWhiteSpace([string]$o.aiAnalysis) -or ([string]$o.aiAnalysis).Length -lt 40 -or [string]::IsNullOrWhiteSpace([string]$o.execution) -or ([string]$o.execution).Length -lt 20 -or $null -eq $o.returnReceipt -or $null -eq $o.evidence){throw "BLOCKED_WEB_RESPONSE_STAGE_EVIDENCE_INCOMPLETE:$key"}};$responses.Add($entry)};$hashes+=,[ordered]@{path=$path.Replace('\','/');sha256=(Get-FileHash $full -Algorithm SHA256).Hash.ToLowerInvariant()}}
$ordered=@($responses|Sort-Object @{e={[string]$_.phase}},@{e={[string]$_.generationMode}},@{e={[int]$_.round}})
$out=[ordered]@{schemaVersion=1;recordType='AiWebDesignModelResponse';providerRunId=$ProviderRunId;taskId=$TaskId;responses=$ordered;sourceResponses=$hashes;aggregation=[ordered]@{mode='lossless-stage-concatenation';generatedFields=@();deduplicated=$false;identityKey='phase|generationMode|round'}}
$fullOut=Resolve-Path (Split-Path (Join-Path $root $OutputPath) -Parent) -ErrorAction SilentlyContinue;if($null -eq $fullOut){$dir=[IO.Path]::GetFullPath((Join-Path $root (Split-Path $OutputPath -Parent)));New-Item -ItemType Directory -Force $dir|Out-Null};$target=[IO.Path]::GetFullPath((Join-Path $root $OutputPath));[IO.File]::WriteAllText($target,($out|ConvertTo-Json -Depth 80),[Text.UTF8Encoding]::new($false));[pscustomobject]@{status='aggregated';providerRunId=$ProviderRunId;stageCount=$ordered.Count;outputPath=$target;sourceCount=$hashes.Count} 
