[CmdletBinding(SupportsShouldProcess)]
param(
  [Parameter(Mandatory)][string]$PackageRoot,
  [Parameter(Mandatory)][string]$TargetRoot,
  [switch]$ForceRepair
)
$ErrorActionPreference='Stop';$manifestPath=Join-Path $PackageRoot 'ES/Automation/ABCD/es-abcd-portable-package.manifest.json';if(-not(Test-Path -LiteralPath $manifestPath -PathType Leaf)){throw 'ABCD_PACKAGE_MANIFEST_MISSING'}
$m=Get-Content -LiteralPath $manifestPath -Raw -Encoding UTF8|ConvertFrom-Json;$missingDirs=[Collections.Generic.List[string]]::new();$missingFiles=[Collections.Generic.List[string]]::new();$mismatch=[Collections.Generic.List[string]]::new();$repaired=[Collections.Generic.List[string]]::new();$sourceFileCount=0;$targetFileCount=0
foreach($d in @($m.requiredDirectories)){if(-not(Test-Path -LiteralPath (Join-Path $PackageRoot $d) -PathType Container)){[void]$missingDirs.Add($d);continue};$td=Join-Path $TargetRoot $d;if(-not(Test-Path -LiteralPath $td -PathType Container)){New-Item -ItemType Directory -Force -Path $td|Out-Null}}
foreach($f in @($m.anchorFiles)){$src=Join-Path $PackageRoot $f;$dst=Join-Path $TargetRoot $f;if(-not(Test-Path -LiteralPath $src -PathType Leaf)){[void]$missingFiles.Add($f);continue};if(-not(Test-Path -LiteralPath $dst -PathType Leaf)){if($PSCmdlet.ShouldProcess($dst,'restore missing ABCD anchor')){New-Item -ItemType Directory -Force -Path (Split-Path $dst)|Out-Null;Copy-Item -LiteralPath $src -Destination $dst -Force;[void]$repaired.Add($f)}}elseif((Get-FileHash $src -Algorithm SHA256).Hash -ne (Get-FileHash $dst -Algorithm SHA256).Hash){[void]$mismatch.Add($f);if($ForceRepair -and $PSCmdlet.ShouldProcess($dst,'replace mismatched ABCD anchor')){Copy-Item -LiteralPath $src -Destination $dst -Force;[void]$repaired.Add($f)}}}
foreach($d in @($m.requiredDirectories)){$srcDir=Join-Path $PackageRoot $d;if(-not(Test-Path -LiteralPath $srcDir -PathType Container)){continue};foreach($src in @(Get-ChildItem -LiteralPath $srcDir -Recurse -File)){$sourceFileCount++;$rel=$src.FullName.Substring($PackageRoot.Length+1).Replace('\','/');$dst=Join-Path $TargetRoot $rel;if(Test-Path -LiteralPath $dst -PathType Leaf){$targetFileCount++;if((Get-FileHash $src.FullName -Algorithm SHA256).Hash -ne (Get-FileHash $dst -Algorithm SHA256).Hash){if($m.anchorFiles -contains $rel){continue};[void]$mismatch.Add($rel);if($ForceRepair -and $PSCmdlet.ShouldProcess($dst,'replace mismatched ABCD file')){Copy-Item -LiteralPath $src.FullName -Destination $dst -Force;[void]$repaired.Add($rel)}}}else{if($PSCmdlet.ShouldProcess($dst,'restore missing ABCD file')){New-Item -ItemType Directory -Force -Path (Split-Path $dst)|Out-Null;Copy-Item -LiteralPath $src.FullName -Destination $dst -Force;[void]$repaired.Add($rel)}else{[void]$missingFiles.Add($rel)}}}}
$status=if($missingDirs.Count -or $missingFiles.Count){'package-invalid'}elseif($mismatch.Count -and -not $ForceRepair){'review-required'}else{'restored-or-present'};[ordered]@{schemaVersion=1;packageId=$m.packageId;status=$status;targetRoot=(Resolve-Path $TargetRoot).Path;sourceFileCount=$sourceFileCount;targetFileCountBeforeRepair=$targetFileCount;missingDirectories=@($missingDirs);missingFiles=@($missingFiles|Select-Object -Unique);missingAnchorFiles=@($missingFiles|Where-Object{$m.anchorFiles -contains $_});hashMismatches=@($mismatch|Select-Object -Unique);repaired=@($repaired|Select-Object -Unique);coreCapabilityGapForbidden=$true;runtimeStatus='not-run';claimsNotProven=@('Unity Runtime','PlayMode','Profiler','Player/Release');authority='ABCD-final-decision'}|ConvertTo-Json -Depth 10 
