[CmdletBinding()]
param([string]$OutputPath='ES/Output/WebPageStudio/bootstrap/abcd-web-execution-receipt.json',[Parameter(Mandatory=$true)][string]$TaskPath,[Parameter(Mandatory=$true)][string]$RoutePath,[Parameter(Mandatory=$true)][string]$RoutePlanPath,[Parameter(Mandatory=$true)][string]$BindingPath,[Parameter(Mandatory=$true)][string]$ArtifactPath,[Parameter(Mandatory=$true)][string]$ModelResponsePath,[ValidateSet('deep-creative-engineering','creative-divergence','engineering','stable')][string]$GenerationProfile='deep-creative-engineering',[switch]$RequireFullAbcd,[Parameter(Mandatory=$true)][string]$Round01Path,[Parameter(Mandatory=$true)][string]$Round02Path,[Parameter(Mandatory=$true)][string]$Round03Path,[Parameter(Mandatory=$true)][string]$Round04Path,[Parameter(Mandatory=$true)][string]$Round05Path,[string]$AiDesignTaskOutputPath='ES/Output/WebPageStudio/bootstrap/ai-web-design-task.json')
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
if($RequireFullAbcd){$GenerationProfile='deep-creative-engineering'}
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDOrchestrator.psm1') -Force
$task=Get-Content (Join-Path $root $TaskPath) -Raw -Encoding UTF8|ConvertFrom-Json
$route=Get-Content (Join-Path $root $RoutePath) -Raw -Encoding UTF8|ConvertFrom-Json
$binding=Get-Content (Join-Path $root $BindingPath) -Raw -Encoding UTF8|ConvertFrom-Json
$routePlanFull=Join-Path $root $RoutePlanPath;if(-not(Test-Path -LiteralPath $routePlanFull -PathType Leaf)){throw "BLOCKED_GITHUB_ABCD_ROUTE_PLAN_MISSING:$RoutePlanPath"};$routePlan=Get-Content $routePlanFull -Raw -Encoding UTF8|ConvertFrom-Json
$expectedTaskId=[string]$task.taskId;if([string]$route.taskId -cne $expectedTaskId){throw "BLOCKED_GITHUB_ABCD_TASK_ROUTE_MISMATCH:$($route.taskId)"};if([string]$binding.taskId -cne $expectedTaskId){throw "BLOCKED_GITHUB_ABCD_TASK_BINDING_MISMATCH:$($binding.taskId)"};if([string]$routePlan.taskId -and [string]$routePlan.taskId -cne $expectedTaskId){throw "BLOCKED_GITHUB_ABCD_TASK_ROUTE_PLAN_MISMATCH:$($routePlan.taskId)"}
$bindingHash=(Get-FileHash (Join-Path $root $BindingPath) -Algorithm SHA256).Hash.ToLowerInvariant()
$upstream=@();$roundPaths=@($Round01Path,$Round02Path,$Round03Path,$Round04Path,$Round05Path);for($ri=0;$ri -lt $roundPaths.Count;$ri++){$rp=Join-Path $root $roundPaths[$ri];if(-not(Test-Path -LiteralPath $rp -PathType Leaf)){throw "BLOCKED_GITHUB_ABCD_UPSTREAM_ROUND_MISSING:$($roundPaths[$ri])"};$bytes=[IO.File]::ReadAllBytes($rp);try{$content=[Text.UTF8Encoding]::new($false,$true).GetString($bytes)}catch{throw "BLOCKED_GITHUB_ABCD_UPSTREAM_ROUND_UTF8_INVALID:$($roundPaths[$ri])"};$sha=[Security.Cryptography.SHA256]::Create();$hash=(-join ($sha.ComputeHash($bytes)|ForEach-Object{$_.ToString('x2')}));$sha.Dispose();$upstream+=[ordered]@{round=$ri+1;path=$roundPaths[$ri].Replace('\','/');hash=$hash;role=@('requirement-intake','focus-context','task-context','knowledge-route','capability-design')[$ri];contentEncoding='utf-8';byteLength=$bytes.Length;content=$content}}
$sourceHash=[string]$task.sourceScopeHash;if($sourceHash -notmatch '^[a-f0-9]{64}$'){throw 'source-scope-hash-missing'}
$round1Doc=Get-Content (Join-Path $root $Round01Path) -Raw -Encoding UTF8|ConvertFrom-Json;$round2Doc=Get-Content (Join-Path $root $Round02Path) -Raw -Encoding UTF8|ConvertFrom-Json
$taskIntent=[string]$binding.taskIntent;if([string]::IsNullOrWhiteSpace($taskIntent)){$taskIntent=[string]$task.taskIntent};if([string]::IsNullOrWhiteSpace($taskIntent)){throw 'BLOCKED_GITHUB_ABCD_TASK_INTENT_MISSING'}
$selectedSeed=@($binding.divergenceCandidates|Where-Object{[string]$_.decision -ceq 'selected'}|Select-Object -First 1);$aiTask=[ordered]@{schemaVersion=1;recordType='AiWebDesignTask';taskId=[string]$task.taskId;requirementSnapshot=[ordered]@{taskIntent=$taskIntent;rawPrompt=[string]$round1Doc.rawPrompt;focus=[string]$round2Doc.focus;goalRevisionHash=[string]$task.goalRevisionHash;sourceScopeHash=$sourceHash};upstreamRounds=$upstream;round05DesignPacket=[ordered]@{path=$Round05Path.Replace('\','/');hash=($upstream|Where-Object round -eq 5).hash};abcdDecision=[ordered]@{invocationId='pending-model-response';selectedCandidateId=if($selectedSeed){[string]$selectedSeed.id}else{'unselected'};decision='revise';source='round-05-capability-design'};allowedWriteRoots=@('ES/Output/WebPageStudio/artifacts');requiredReads=@($upstream|ForEach-Object{$_.path})+@('ES/AISpace/README.md','ES/AISpace/Public/WebPageStudio/20260829/README.md');requiredChecks=@('build','interaction-replay','responsive-replay','a11y','utf8');maxIterations=5;stopConditions=@('no-unresolved-critical-findings','all-required-checks-pass','user-directed-stop')};$aiTaskFull=Join-Path $root $AiDesignTaskOutputPath;$aiTaskDir=Split-Path -Parent $aiTaskFull;if(-not(Test-Path $aiTaskDir)){New-Item -ItemType Directory $aiTaskDir -Force|Out-Null};[IO.File]::WriteAllText($aiTaskFull,($aiTask|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false))
if([string]::IsNullOrWhiteSpace($ModelResponsePath)){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_REQUIRED'}
$modelResponseFull=Join-Path $root $ModelResponsePath;if(-not(Test-Path -LiteralPath $modelResponseFull -PathType Leaf)){throw "BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_MISSING:$ModelResponsePath"}
$modelDoc=Get-Content -Raw -Encoding UTF8 $modelResponseFull|ConvertFrom-Json
if([string]$modelDoc.recordType -cne 'AiWebDesignModelResponse' -or @($modelDoc.responses).Count -lt 1){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_INVALID'}
if([string]::IsNullOrWhiteSpace([string]$modelDoc.taskId) -or [string]$modelDoc.taskId -cne [string]$task.taskId){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_TASK_ID_MISMATCH'}
if([string]::IsNullOrWhiteSpace([string]$modelDoc.providerRunId) -or [string]$modelDoc.providerRunId -match '(?i)normalized-|synthetic|fixture|test-provider'){throw 'BLOCKED_GITHUB_ABCD_PROVIDER_ID_INVALID'}
$responseIdentityKeys=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($identity in @($modelDoc.responses)){ $identityKey=('{0}|{1}|{2}' -f [string]$identity.phase,[string]$identity.generationMode,[int]$identity.round);if(-not $responseIdentityKeys.Add($identityKey)){throw "BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_DUPLICATE_STAGE:$identityKey"} }
foreach($resp in @($modelDoc.responses)){
  if([string]::IsNullOrWhiteSpace([string]$resp.phase) -or [string]$resp.generationMode -notin @('creative-divergence','engineering','stable') -or [int]$resp.round -lt 0 -or @($resp.outputs).Count -lt 1){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_INVALID'}
  foreach($o in @($resp.outputs)){
    if([string]::IsNullOrWhiteSpace([string]$o.aiAnalysis) -or ([string]$o.aiAnalysis).Length -lt 40 -or [string]::IsNullOrWhiteSpace([string]$o.execution) -or ([string]$o.execution).Length -lt 20 -or $null -eq $o.returnReceipt -or $null -eq $o.evidence){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_EVIDENCE_INCOMPLETE'}
    if($null -eq $o.candidate -or [string]::IsNullOrWhiteSpace([string]$o.candidate.content)){throw 'BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_CANDIDATE_REQUIRED'}
  }
}
$requiredResponses=@([pscustomobject]@{phase='seed-selection';mode=if($GenerationProfile -eq 'engineering' -or $GenerationProfile -eq 'stable'){$GenerationProfile}else{'creative-divergence'};round=0})
if($GenerationProfile -eq 'deep-creative-engineering' -or $GenerationProfile -eq 'creative-divergence'){$requiredResponses+=1..12|ForEach-Object{[pscustomobject]@{phase='tree-expansion';mode='creative-divergence';round=$_}};$requiredResponses+=@('player-replay','complexity-prune','candidate-tournament','final-decision')|ForEach-Object{[pscustomobject]@{phase=$_;mode='creative-divergence';round=1}};1..3|ForEach-Object{$requiredResponses+=[pscustomobject]@{phase='counterplay-audit';mode='creative-divergence';round=$_}}}
if($GenerationProfile -eq 'deep-creative-engineering'){$requiredResponses+=1..3|ForEach-Object{[pscustomobject]@{phase='engineering-architecture-divergence';mode='engineering';round=$_}}}
$missingResponses=@($requiredResponses|Where-Object{$q=$_;@($modelDoc.responses|Where-Object{[string]$_.phase -ceq $q.phase -and [string]$_.generationMode -ceq $q.mode -and [int]$_.round -eq [int]$q.round}).Count -eq 0});if($missingResponses.Count -gt 0){$summary=($missingResponses|ForEach-Object{"$($_.phase)/$($_.mode)/$($_.round)"}) -join ',';throw "BLOCKED_GITHUB_ABCD_MODEL_RESPONSE_PHASES_MISSING:$summary"}
$responseQueue=@($modelDoc.responses);$responseIndex=0
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCInnovationRun.psm1') -Force
Import-Module (Join-Path $root 'ES/Automation/ABCD/ESABCDCapabilityDispatcher.psm1') -Force
$null=Get-Command New-ESABCDModelResponseInvoker -ErrorAction Stop
$responseInvoker=New-ESABCDModelResponseInvoker -Responses $responseQueue
$modelInvoker={param($ctx);$responseIndex++;& $responseInvoker $ctx}.GetNewClosure()
$creative=$null;$innovation=$null
if($GenerationProfile -eq 'deep-creative-engineering' -or $GenerationProfile -eq 'creative-divergence'){$creative=Invoke-ESABCInnovationRun -Requirement $taskIntent -GoalRevision ([string]$task.goalRevisionHash) -SourceHash $sourceHash -GenerationMode 'creative-divergence' -ModelInvoker $modelInvoker -SeedBranches @($bindingHash) -SeedConstraints @('preserve repository scanability and keyboard reachability') -ProjectRoot $root;if([string]$creative.status -cne 'completed'){throw 'BLOCKED_GITHUB_ABCD_CREATIVE_RUN_NOT_COMPLETED'}}
if($GenerationProfile -eq 'deep-creative-engineering'){$creativeBranch=$creative.divergenceTree[[string]$creative.finalDecision.selectedBranchId];$innovation=Invoke-ESABCInnovationRun -Requirement $taskIntent -GoalRevision ([string]$task.goalRevisionHash) -SourceHash $sourceHash -GenerationMode 'engineering' -ModelInvoker $modelInvoker -SeedBranches @($creativeBranch.content) -SeedConstraints @('preserve repository scanability and keyboard reachability','challenge creative assumptions with implementation evidence') -ProjectRoot $root}
elseif($GenerationProfile -eq 'engineering' -or $GenerationProfile -eq 'stable'){$innovation=Invoke-ESABCInnovationRun -Requirement $taskIntent -GoalRevision ([string]$task.goalRevisionHash) -SourceHash $sourceHash -GenerationMode $GenerationProfile -ModelInvoker $modelInvoker -SeedBranches @($bindingHash) -SeedConstraints @('preserve repository scanability and keyboard reachability') -ProjectRoot $root}
else{$innovation=$creative}
if($null -eq $innovation -or [string]$innovation.status -cne 'completed'){throw 'BLOCKED_GITHUB_ABCD_INNOVATION_RUN_NOT_COMPLETED'}
$taskBindingId=[string]$task.taskBindingId;if([string]::IsNullOrWhiteSpace($taskBindingId)){$taskBindingId=if($binding.PSObject.Properties['taskBindingId']){[string]$binding.taskBindingId}else{[string]$binding.bindingId}};if([string]::IsNullOrWhiteSpace($taskBindingId)){throw 'BLOCKED_GITHUB_ABCD_TASK_BINDING_ID_MISSING'}
$authorizationRef=[string]$task.authorizationRef;if([string]::IsNullOrWhiteSpace($authorizationRef)){$authorizationRef=[string]$binding.authorizationRef};if([string]::IsNullOrWhiteSpace($authorizationRef)){throw 'BLOCKED_GITHUB_ABCD_AUTHORIZATION_REF_MISSING'}
$store=New-ESABCDOrchestrationStore -TaskId $task.taskId -TaskBindingId $taskBindingId -TaskBindingHash $bindingHash -AuthorizationRef $authorizationRef -TaskRevision ([int]$task.taskRevision) -ContextVersion ([int]$task.contextVersion) -RoutePlanHash ([string]$routePlan.routePlanHash) -SourceScopeHash $sourceHash -MaxRounds 3 -AttemptsPerRound 2
$null=Start-ESABCDIterationRound $store ([int]$task.taskRevision) ([int]$task.contextVersion)
function Add-Candidate([string]$Id,[string]$Assumption){$snap=Get-ESABCDHash ([ordered]@{taskId=$store.taskId;branch=$Id;assumption=$Assumption;route=$store.routePlanHash});Add-ESABCDCandidate $store $Id $null $snap $Assumption 'static-design-and-existing-artifact-check' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null;return $snap}
$candidates=@();foreach($branch in @($innovation.divergenceTree.Values)){$candidates+=Add-Candidate ([string]$branch.branchId) ([string]$branch.content)}
$evidence=@([pscustomobject]@{path=$BindingPath.Replace('\\','/');sha256=$bindingHash})
Add-ESABCDAuditRecord $store ([string]$innovation.finalDecision.selectedBranchId) 'abcd-auditor:static-quality' 'review' $evidence 'abcd-verifier:design-contract' $authorizationRef (Get-ESABCDHash 'verifier-definition-v1') ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
Select-ESABCDDecision $store ([string]$innovation.finalDecision.selectedBranchId) retry 'full' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
$cycleId=('cycle-1-'+[string]$task.taskId);$cycle=Start-ESABCDCorrectionCycle $store $cycleId $RoutePath 'evidence' retry 'full' 1 ([int]$store.taskRevision) ([int]$store.contextVersion)
$receiptRef=$RoutePath.Replace('\\','/');$receiptHash=(Get-FileHash (Join-Path $root $receiptRef) -Algorithm SHA256).Hash.ToLowerInvariant();Add-ESABCDVerificationReceipt $store $cycleId review $receiptRef $receiptHash ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
Stop-ESABCDIteration $store 'ABCD candidate tournament completed; selected candidate requires next correction/design pass.' ([int]$store.taskRevision) ([int]$store.contextVersion)|Out-Null
if(-not (Test-ESABCDEventStoreIntegrity $store)){throw 'abcd-event-store-integrity-failed'}
$snapPath=Join-Path $root 'ES/Output/WebPageStudio/bootstrap/abcd-github-web-snapshot.json';Save-ESABCDOrchestrationSnapshot $store $snapPath|Out-Null
$creativeRunId=if($creative){[string]$creative.runId}else{$null};$creativeRunHash=if($creative){[string]$creative.runHash}else{$null};$engineeringRunId=if($GenerationProfile -eq 'deep-creative-engineering'){[string]$innovation.runId}else{$null};$engineeringRunHash=if($GenerationProfile -eq 'deep-creative-engineering'){[string]$innovation.runHash}else{$null}
$artifactFull=Join-Path $root $ArtifactPath;$out=[ordered]@{schemaVersion=1;recordType='ABCDOrchestrationRunReceipt';invocationId=('abcd-invocation-'+$store.taskId);taskId=$store.taskId;innovationRunId=$innovation.runId;innovationRunHash=$innovation.runHash;modelResponsePath=$ModelResponsePath.Replace('\\','/');modelResponseHash=(Get-FileHash $modelResponseFull -Algorithm SHA256).Hash.ToLowerInvariant();modelInvokerCalls=$responseIndex;aiDesignTaskPath=$AiDesignTaskOutputPath.Replace('\\','/');aiDesignTaskHash=(Get-FileHash $aiTaskFull -Algorithm SHA256).Hash.ToLowerInvariant();upstreamRounds=$upstream;routePlanHash=$store.routePlanHash;sourceScopeHash=$store.sourceScopeHash;eventSequence=@($store.events).Count;eventHashes=@($store.events|ForEach-Object { $_.eventHash });candidateCount=$candidates.Count;candidateHashes=$candidates;selectedCandidateId=$innovation.finalDecision.selectedBranchId;decision='retry';existingArtifactBindings=@([pscustomobject]@{path=$BindingPath.Replace('\\','/');sha256=$bindingHash},[pscustomobject]@{path=$ArtifactPath.Replace('\\','/');sha256=(Get-FileHash $artifactFull -Algorithm SHA256).Hash.ToLowerInvariant()});snapshotPath='ES/Output/WebPageStudio/bootstrap/abcd-github-web-snapshot.json';snapshotHash=(Get-FileHash $snapPath -Algorithm SHA256).Hash.ToLowerInvariant();status='completed-with-retry-decision';integrityVerified=$true;nonClaims=@('model response artifact is not proof of provider identity','not HTML acceptance','not runtime/network/release')};[IO.File]::WriteAllText((Join-Path $root $OutputPath),($out|ConvertTo-Json -Depth 40),[Text.UTF8Encoding]::new($false));$out|Select-Object recordType,invocationId,innovationRunId,modelInvokerCalls,candidateCount,selectedCandidateId,decision,status,integrityVerified
$receiptFull=Join-Path $root $OutputPath;if(Test-Path -LiteralPath $receiptFull){$receiptDoc=Get-Content $receiptFull -Raw -Encoding UTF8|ConvertFrom-Json;$receiptDoc|Add-Member -NotePropertyName creativeInnovationRunId -NotePropertyValue $creativeRunId -Force;$receiptDoc|Add-Member -NotePropertyName engineeringInnovationRunId -NotePropertyValue $engineeringRunId -Force;$receiptDoc|Add-Member -NotePropertyName creativeRunHash -NotePropertyValue $creativeRunHash -Force;$receiptDoc|Add-Member -NotePropertyName engineeringRunHash -NotePropertyValue $engineeringRunHash -Force;[IO.File]::WriteAllText($receiptFull,($receiptDoc|ConvertTo-Json -Depth 40),[Text.UTF8Encoding]::new($false))} 
