[CmdletBinding()]
param([string]$ProjectRoot)
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path}
Import-Module (Join-Path $ProjectRoot 'ES/Automation/ABCD/ESABCInnovationRun.psm1') -Force
$h=('a'*64)
$verificationOutput='dimension-ok';$verificationOutputHash=([Security.Cryptography.SHA256]::Create().ComputeHash([Text.Encoding]::UTF8.GetBytes($verificationOutput))|ForEach-Object ToString x2)-join ''
$generator={param($ctx)
 $capturedUtc=[DateTime]::UtcNow.ToString('o')
 $parents=@($ctx.previousDirections|ForEach-Object {[string]$_.architectureId}|Select-Object -First 2);if($parents.Count -lt 2){$parents=@('seed-a','seed-b')}
 $items=@();foreach($i in 1..6){$inc=if($i -eq 1){1}else{$i-1};$cf=@(1..3|ForEach-Object{[pscustomobject]@{round=$_;baselineOutcome="baseline-$($_)-$i";candidateOutcome="candidate-$($_)-$i";baselineScore=2;candidateScore=$inc;qualitativeDifference="different-$($_)-$i"}});$items+=[pscustomobject][ordered]@{architectureId="g$($ctx.round)-arch-$i";generationReceipt=[pscustomobject]@{providerRunId="provider-$($ctx.round)-$i";requestHash=('a'*64);responseHash=('b'*64);capturedUtc=$capturedUtc};implementationBoundary='bounded';lifecycleAssessment='lifecycle';performanceAssessment='performance';networkAssessment='network';debuggingAssessment='debug';editorProductionAssessment='editor';innovationDifferentialAssessment='qualitative-difference';innovationDifferentialLevel=[math]::Min(5,$i);counterfactualRegression=$cf;fusionParentIds=$parents;baselinePlayerLevel=2;playerIncrementDelta=$inc-2;playerIncrementRegression=$inc;technicalInnovationLevel=[math]::Min(5,$i);safetyLevel=3;performanceLevel=[math]::Min(5,$i);reusabilityLevel=[math]::Min(5,$i);lifecycleLevel=[math]::Min(5,$i);networkLevel=[math]::Min(5,$i);debuggingLevel=[math]::Min(5,$i);editorProductionLevel=[math]::Min(5,$i)}};$items
}
$base=$generator
$generator={param($ctx)$out=@(& $base $ctx);foreach($x in $out){$de=@('lifecycle','performance','network','debugging','editorProduction')|ForEach-Object{[pscustomobject]@{dimension=$_;metric='metric';target='target';observed='observed';verificationRef='verify';status='verified';evidenceHash=('a'*64);verificationReceipt=[pscustomobject]@{status='passed';exitCode=0;output=$verificationOutput;outputHash=$verificationOutputHash}}};Add-Member -InputObject $x -NotePropertyName dimensionEvidence -NotePropertyValue @($de) -Force};$out}
$wrappedGenerator=$generator;$generator={param($ctx)$items=@(& $wrappedGenerator $ctx);foreach($x in $items){$x.generationReceipt.requestHash=$ctx.requestHash};$items}
$r=Invoke-ESABCEngineeringArchitectureCompetition -Requirement '工程架构竞争' -GoalRevision 'goal-r1' -SourceHash $h -ModelInvoker $generator -ProjectRoot $ProjectRoot
$badParentInvoker={param($ctx)& $base $ctx}
$bad=$false;try{Invoke-ESABCEngineeringArchitectureCompetition -Requirement '工程架构竞争' -GoalRevision 'goal-r1' -SourceHash $h -ModelInvoker $badParentInvoker -ProjectRoot $ProjectRoot|Out-Null}catch{$bad=$true}
$pass=($r.status -eq 'review-required' -and $r.generationCount -eq 3 -and $r.directionCount -ge 15 -and @($r.paretoShortlist).Count -ge 2 -and @($r.discarded|Where-Object {$_.reason -eq 'SAFE_BUT_NO_PLAYER_INCREMENT'}).Count -ge 1 -and $r.winnerId -and $r.implementationEvidenceRequiredForFinal -and $bad)
[pscustomobject]@{status=if($pass){'passed'}else{'failed'};directionCount=$r.directionCount;paretoCount=@($r.paretoShortlist).Count;safeNoIncrementRejected=@($r.discarded|Where-Object {$_.reason -eq 'SAFE_BUT_NO_PLAYER_INCREMENT'}).Count;completionEligible=$r.completionEligible;invalidFusionRejected=$bad;counterfactualRegression=($r.evidenceSummary.counterfactualPositiveCount -gt 0);contractHashBinding=($r.contractHash -match '^[a-f0-9]{64}$')}
$hashMismatch=$false;$badHashGenerator={param($ctx)$items=@(& $generator $ctx);foreach($x in $items){$x.generationReceipt.requestHash=('c'*64)};$items};try{Invoke-ESABCEngineeringArchitectureCompetition -Requirement '工程架构竞争' -GoalRevision 'goal-r1' -SourceHash $h -ModelInvoker $badHashGenerator -ProjectRoot $ProjectRoot|Out-Null}catch{$hashMismatch=$_.Exception.Message -like '*PARETO*'};$staleBlocked=$false;$staleGenerator={param($ctx)$items=@(& $generator $ctx);foreach($x in $items){$x.generationReceipt.capturedUtc='2000-01-01T00:00:00Z'};$items};try{Invoke-ESABCEngineeringArchitectureCompetition -Requirement '工程架构竞争' -GoalRevision 'goal-r1' -SourceHash $h -ModelInvoker $staleGenerator -ProjectRoot $ProjectRoot|Out-Null}catch{$staleBlocked=$_.Exception.Message -like '*PARETO*'};$pass=($pass -and $hashMismatch -and $staleBlocked);if(-not $pass){exit 1} 
